DROP TABLE logs;

CREATE TABLE logs (
    command VARCHAR(255),
    table_name VARCHAR(100),
    username VARCHAR(100),
    change_date VARCHAR(100),
    change_time VARCHAR(100)
);


CREATE OR REPLACE TRIGGER dummy AFTER INSERT ON DEP FOR EACH ROW
BEGIN
    INSERT INTO logs VALUES ('INSERT', 'DEP', user, sysdate, CURRENT_TIMESTAMP);
END;
/

INSERT INTO DEP VALUES(92);
INSERT INTO DEP VALUES(23);
INSERT INTO DEP VALUES(5);

SELECT * FROM logs;
