DROP TABLE sal1;
DROP TABLE cust1;
DROP TABLE ord1;


CREATE TABLE sal1 AS SELECT * FROM sal;
CREATE TABLE cust1 AS SELECT * FROM cust;
CREATE TABLE ord1 AS SELECT * FROM ord;

START TRANSACTION;
DELETE FROM sal1;
DELETE FROM cust1;
TRUNCATE TABLE ord1;

ROLLBACK;

SELECT * FROM sal1;
SELECT * FROM cust1;
SELECT * FROM ord1
