lecture1:
	gcc lecture1.c -o main && ./main && rm main
lecture2:
	gcc lecture2.c -o main && ./main && rm main

lecture3:
	gcc lecture3.c -o main && ./main && rm main
2:
	g++ 2.cpp -o main && ./main && rm main
3:
	g++ 3.cpp -o main && ./main && rm main

clean:
	rm main